### ISSUE TITLE
Could you please explain the underlying principles of the implementation?

### ISSUE THREAD

**Issue by MaggieNgWu** [Shigoto-dev19/sha256-o1js#1]
I am working on a project that also greatly needs the functionality you are developing. Could we discuss how you plan to implement it? I would like to collaborate with you.

**Comment by Shigoto-dev19** [comment]
Hello @MaggieNgWu, 
- I have written this [notion page](https://smooth-writer-db1.notion.site/Understanding-SHA-256-Hash-Function-274efa15d9a546aa9cacde9c4d8eb953) to break down SHA256. 
  - I hope it helps you understand the mechanism of the hash function in general!
- Recently, the o1js team released efficient bitwise gadgets that help develop SHA256 swiftly.
- I think the o1js team will soon release the SHA256 hash function as a gadget as well.
- I am putting the last touches on my SHA256 repo, but I think it won't be as efficient as the to-be-released o1js SHA256, so I wouldn't recommend using it for your protocol.
- The work is mostly done for this project, however, I am open to any further questions if you still want to implement it yourself :)
